services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    # privileged: false
    # network_mode: host
    ports:
      - "8123:8123"
    volumes:
      # Mount HA configuration
      - ./homeassistant/config:/config
    environment:
      - TZ=Europe/Berlin
